storagenetwork = false
tconstruct = false
sophisticatedbackpacks = true
fastfurnace = false
craftingstation = false
ironfurnaces = false
jei = true
refinedstorageaddons = false
craftingcraft = false
toms_storage = false
refinedstorage = false
prettypipes = true
fastbench = false
cyclic = false
appliedenergistics2 = false

