#Enable the basic quiver?
enableBasic = true
#Enable the iron quiver?
enableIron = true
#Enable the copper quiver?
enableCopper = true
#Enable the silver quiver?
enableSilver = true
#Enable the gold quiver?
enableGold = true
#Enable the diamond quiver?
enableDiamond = true
#Enable the obsidian quiver?
enableObsidian = true
#Fireproof the basic quiver?
fireproofBasic = true
#Fireproof the iron quiver?
fireproofIron = true
#Fireproof the copper quiver?
fireproofCopper = true
#Fireproof the silver quiver?
fireproofSilver = true
#Fireproof the gold quiver?
fireproofGold = true
#Fireproof the diamond quiver?
fireproofDiamond = true
#Fireproof the obsidian quiver?
fireproofObsidian = true
#How many rows does the basic quiver have?
#Range: 1 ~ 13
rowsBasic = 1
#How many rows does the iron quiver have?
#Range: 1 ~ 13
rowsIron = 1
#How many rows does the copper quiver have?
#Range: 1 ~ 13
rowsCopper = 1
#How many rows does the silver quiver have?
#Range: 1 ~ 13
rowsSilver = 1
#How many rows does the gold quiver have?
#Range: 1 ~ 13
rowsGold = 1
#How many rows does the diamond quiver have?
#Range: 1 ~ 13
rowsDiamond = 1
#How many rows does the Netherite quiver have?
#Range: 1 ~ 13
rowsNetherite = 1
#How many columns does the basic quiver have?
#Range: 1 ~ 13
columnsBasic = 2
#How many columns does the iron quiver have?
#Range: 1 ~ 13
columnsIron = 4
#How many columns does the copper quiver have?
#Range: 1 ~ 13
columnsCopper = 3
#How many columns does the silver quiver have?
#Range: 1 ~ 13
columnsSilver = 3
#How many columns does the gold quiver have?
#Range: 1 ~ 13
columnsGold = 3
#How many columns does the diamond quiver have?
#Range: 1 ~ 13
columnsDiamond = 5
#How many columns does the Netherite quiver have?
#Range: 1 ~ 13
columnsNetherite = 6
#Range: -1000 ~ 1000
xPos = 76
#Range: -1000 ~ 1000
yPos = 24

