
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 915197
	#The name of the modpack
	modpackName = "Magnivicent Modpack"
	#The version of the modpack
	modpackVersion = "3.0.3-alpha"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = true

