
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 915197
	#The name of the modpack
	modpackName = "Magnivicent World"
	#The version of the modpack
	modpackVersion = "7.0.0-prealpha-1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

